In [2]:
#NUMPY ASSIGNMENT

#Topic: NumPy Arrays, Boolean Filtering, "np.where()", and Missing Values.

#QUESTION 1 — Array Analysis
import numpy as np
Scores = np.array([42,67,85,31,74,93,56,48,79,61,37,88])

In [105]:
# Question 1- No:A  
print(Scores)

[42 67 85 31 74 93 56 48 79 61 37 88]


In [146]:
# Question 1No:B 
print(Scores)

[42 67 85 31 74 93 56 48 79 61 37 88]


In [145]:
# Question 1 No:C 
print(np.max(Scores)) 

93


In [144]:
# Question 1 No:D 
print(np.min(Scores))

31


In [140]:
# Question 1 No:E
print(np.sum(Scores))

761


In [141]:
# Question 1 No:F  
print(np.mean(Scores))

63.416666666666664


In [142]:
# Question 1 No: G
print(Scores[Scores >= 60])

[67 85 74 93 79 61 88]


In [143]:
# Question 1  No: H
print(Scores[Scores <= 50])

[42 31 48 37]


In [137]:
# Question 1 No: I
print(np.sum(Scores <= 50))

4


In [136]:
# QUESTION 2 no: a
print( Scores > 60)

[False  True  True False  True  True False False  True  True False  True]


In [135]:
#QUESTION 2 no: b

print( Scores [Scores >= 60])

[67 85 74 93 79 61 88]


In [134]:
#QUESTION 2 no:c

print( Scores [(Scores >= 60) & (Scores < 80)])

[67 74 79 61]


In [133]:
#QUESTION 2 no:d

print( Scores [Scores >= 80])

[85 93 88]


In [132]:
#QUESTION 2 no:e

print( Scores [Scores <= 40])

[31 37]


In [131]:
#QUESTION 2 no: f
print( Scores [Scores <= 60])

[42 31 56 48 37]


In [129]:
#QUESTION 2 - no:g

print( Scores [(Scores >= 80) | (Scores < 40)])

[85 31 93 37 88]


In [130]:
#QUESTION 2 no: h

print( Scores [(Scores >= 60) & (Scores < 90)])

[67 85 74 79 61 88]


In [69]:
# QUESTION 3 - NP.WHERE()

#Q No: A
result = np.where (Scores >= 50, "pass", "fail")
print(result)

['fail' 'pass' 'pass' 'fail' 'pass' 'pass' 'pass' 'fail' 'pass' 'pass'
 'fail' 'pass']


In [128]:
# QUESTION 3 No: B

import numpy as np
Scores = np.array([42,67,85,31,74,93,56,48,79,61,37,88])

result = np.where(Scores >= 80, "execellent", "Not Execellent")
print(result)

['Not Execellent' 'Not Execellent' 'execellent' 'Not Execellent'
 'Not Execellent' 'execellent' 'Not Execellent' 'Not Execellent'
 'Not Execellent' 'Not Execellent' 'Not Execellent' 'execellent']


In [80]:
# QUESTION 3 No: C

grade = np.where(
    Scores >= 70, "A",
    np.where(
        Scores >= 60, "B",
        np.where( 
            Scores >= 50 , "C", "F"
        )
    )
)
print(grade)

['F' 'B' 'A' 'F' 'A' 'A' 'C' 'F' 'A' 'B' 'F' 'A']


In [70]:
# QUESTION 4 - Challenge: Multiple Conditions

import numpy as np

Result = np.array([35,52,68,74,81,45,59,92,63,39,77,86])
print(Result)

[35 52 68 74 81 45 59 92 63 39 77 86]


In [37]:
# QUESTION 4 No: A

print(Result [Result >=70])

[74 81 92 77 86]


In [42]:
# QUESTION 4 No: B

print(Result [(Result > 40) & (Result < 70)]) 

[52 68 45 59 63]


In [43]:
# QUESTION 4 No: C

print(Result [(Result < 40) | (Result > 70)]) 

[35 74 81 92 39 77 86]


In [44]:
# QUESTION 4 No: D

print(Result [(Result > 50) & (Result < 80)]) 

[52 68 74 59 63 77]


In [51]:
# QUESTION 4 No: E
print(np.sum((Result > 50) & (Result < 80)))

6


In [57]:
# QUESTION 4 No: F 
print(np.sum((Result > 70)))

5


In [56]:
# QUESTION 4 No: G
print(np.mean(Result [Result > 70]))

82.0


In [17]:
# QUESTION 5 - Grade Analysis Without Loops

import numpy as np

Results = np.array([35,52,68,74,81,45,59,92,63,39,77,86])
print(Results)

grade = np.where(
     Results >= 70, "A",
    np.where(
        Results >= 60, "B",
        np.where( 
            Results >= 50 , "C", "F"
        )
    )
)
print("\n", grade)

[35 52 68 74 81 45 59 92 63 39 77 86]

 ['F' 'C' 'B' 'A' 'A' 'F' 'C' 'A' 'B' 'F' 'A' 'A']


In [13]:
#Question 5 no: A
print(np.sum(Results > 50))

9


In [16]:
#Question 5 no: B
print(np.sum(Results < 50))

3


In [23]:
#Question 5 no: C
print(np.sum(grade == "A"))

5


In [22]:
#Question 5 no: D
print(np.sum(grade == "B"))

2


In [24]:
#Question 5 no: E
print(np.sum(grade == "C"))

2


In [28]:
#Question 5 no: F
print(np.max(Results))

92


In [29]:
#Question 5 no: G
print(np.min(Results))

35


In [30]:
#Question 5 no: H
print(np.mean(Results))

64.25


In [34]:
#QUESTION 6 - MISSING VALUES

import numpy as np

Nums = np.array([45,67,np.nan,82,54,np.nan,71,39,90,np.nan,63])

In [37]:
#QUESTION 6 no: A
print(Nums)

[45. 67. nan 82. 54. nan 71. 39. 90. nan 63.]


In [39]:
#QUESTION 6 no: B
print(np.isnan(Nums))

[False False  True False False  True False False False  True False]


In [41]:
#QUESTION 6 no: C
print(Nums[np.isnan(Nums)])

[nan nan nan]


In [43]:
#QUESTION 6 no: D

Average_Nums = np.nanmean(Nums)
print(Average_Nums)

63.875


In [44]:
#QUESTION 6 no: E

Average_Nums = np.nanmax(Nums)
print(Average_Nums)

90.0


In [46]:
#QUESTION 6 no: F

Average_Nums = np.nanmin(Nums)
print(Average_Nums)

39.0


In [151]:
#QUESTION 6 no: G


import numpy as np

Nums = np.array([45,67,np.nan,82,54,np.nan,71,39,90,np.nan,63])
Nums_no =np.copy (Nums)
Nums_no[np.isnan(Nums_no)]

array([nan, nan, nan])

In [103]:
#QUESTION 6 no: H
print(Nums_no)

[45. 67. nan 82. 54. nan 71. 39. 90. nan 63.]


In [105]:
#Question 7 - Final Challenge

import numpy as np

Recoreded = np.array([29,47,51,64,72,88,np.nan,93,56,41,np.nan,79,67,35,84])

In [106]:
#QUESTION 7 no: 1
print(Recoreded)

[29. 47. 51. 64. 72. 88. nan 93. 56. 41. nan 79. 67. 35. 84.]


In [107]:
#Question 7 No: 2
print(np.isnan(Recoreded))

[False False False False False False  True False False False  True False
 False False False]


In [108]:
#Question 7 No: 3
print(np.nanmean(Recoreded))

62.0


In [125]:
#Question 7 No: 4
updata_Recored =np.copy (Recoreded)
updata_Recored [np.isnan(Recoreded)]

array([nan, nan])

In [127]:
#Question 7 No: 5
print(updata_Recored)

[29. 47. 51. 64. 72. 88. nan 93. 56. 41. nan 79. 67. 35. 84.]


In [110]:
#Question 7 No: 6
Recoreded = np.where (Scores >= 50, "pass", "fail")
print(Recoreded)

['fail' 'pass' 'pass' 'fail' 'pass' 'pass' 'pass' 'fail' 'pass' 'pass'
 'fail' 'pass']


In [111]:
#Question No: 7

import numpy as np

Recoreded = np.array([29,47,51,64,72,88,np.nan,93,56,41,np.nan,79,67,35,84])

grade =np.where(
  Recoreded > 70, "A",
    np.where(
        Recoreded > 60, "B",
        np.where(
            Recoreded > 50, "C", "F"
        )
    )
)
print(grade)

['F' 'F' 'C' 'B' 'A' 'A' 'F' 'A' 'C' 'F' 'F' 'A' 'B' 'F' 'A']


In [112]:
#Question 7 No: 8

print(Recoreded [Recoreded > 70])

[72. 88. 93. 79. 84.]


In [113]:
#Question 7 No: 9

print(Recoreded [Recoreded < 50])

[29. 47. 41. 35.]


In [152]:
#Question 7 No: 10

print(np.nanmax (Recoreded))

93.0


In [115]:
#Question 7 No: 11

print(np.nanmin (Recoreded))

29.0


In [116]:
#Question 7 No: 12

print(np.nanmean (Recoreded))

62.0


In [122]:
#Question 7 No: 13

print(np.nansum (Recoreded > 50))

9


In [121]:
#Question 7 No: 14

print(np.nansum (Recoreded < 50))

4


In [1]:
#Additional Requirement

#Q1 Answer - In my understanding it's applies a logical mask to extract and return a shorter array containing only the matching valuse, Whille Np.where() performs element wise cinditional transformation the original shape and size of the array.

#Q2 Answer- Np.where() Any arithmetic operation involoving an underfined value, Whille Np.nanmean() Do the Calulates the class average based strictly on the parers that were actully graded.

#Q3 Answers - This mean that the value it's replacing missing entries with 0 introduces extreme downward bias into your dataset.